version: "3.7"
services:
  db:
    container_name: db
    image: postgres:12.2
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db-network
  dbadmin:
    container_name: dbadmin
    image: dpage/pgadmin4:4.21
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8181:80
    networks:
      - db-network
    links:
      - db
    depends_on:
      - db
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        APP_USER: api
    command: tail -f /dev/null
    environment:
      DEBUG: 1
      SECRET_KEY: 'some_secret_random_key'
      DATABASE_URL: 'postgres://postgres:postgres@db/data'
      EMAIL_URL: 'console:'
    volumes:
      - .:/home/api/src/
      - staticfiles:/home/api/src/api/staticfiles
      - mediafiles:/home/api/src/api/mediafiles
    networks:
      - db-network
      - api-network
    links:
      - db
    depends_on:
      - db
  proxy:
    container_name: proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/srv/staticfiles
      - mediafiles:/srv/mediafiles
    ports:
      - 8100:80
    networks:
      - api-network
    links:
      - api
    depends_on:
      - api
volumes:
  db-data:
  staticfiles:
  mediafiles:
networks:
  db-network:
  api-network:
