version: "3.7"
services:
  db:
    container_name: ddt-db
    image: postgres:12.6
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db-network
    ports:
      - 5432:5432
  db-client:
    container_name: template-db-client
    image: sosedoff/pgweb:0.11.8
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/data?sslmode=disable
    ports:
      - 8080:8081
    networks:
      - db-network
    links:
      - db
    depends_on:
      - db
  api:
    container_name: ddt-api
    image: ddt-api-image
    build:
      context: ./api
    env_file: api/.env
    volumes:
      - ./api/staticfiles:/home/django/src/staticfiles
      - ./api/mediafiles:/home/django/src/mediafiles
    networks:
      - db-network
      - proxy-network
    links:
      - db
    depends_on:
      - db
  proxy:
    container_name: ddt-proxy
    image: ddt-proxy-image
    build:
      context: ./proxy
    volumes:
      - ./api/staticfiles:/srv/staticfiles
      - ./api/mediafiles:/srv/mediafiles
    ports:
      - 8000:80
    networks:
      - proxy-network
    links:
      - api
volumes:
  db-data:
networks:
  db-network:
  proxy-network:
