version: "3.7"
services:
  db:
    container_name: db-container
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db-network
  dbadmin:
    container_name: dbadmin-container
    image: dpage/pgadmin4:4.21
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8080:80
    networks:
      - db-network
    links:
      - db
    depends_on:
      - db
  api:
    container_name: api-container
    build:
      context: ./api/
      dockerfile: Dockerfile
      args:
        APP_USER: api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    environment:
      DEBUG: 1
      SECRET_KEY: 'some_secret_random_key'
      DATABASE_URL: 'postgres://postgres:postgres@db/data'
      EMAIL_URL: 'console:'
    volumes:
      - ./api/:/home/api/src/
      - staticfiles:/home/api/src/staticfiles
      - mediafiles:/home/api/src/mediafiles
    networks:
      - db-network
      - api-network
    links:
      - db
    depends_on:
      - db
  proxy:
    container_name: proxy-container
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/srv/staticfiles
      - mediafiles:/srv/mediafiles
    ports:
      - 80:8000
    networks:
      - api-network
    links:
      - api
    depends_on:
      - api
volumes:
  db-data:
  staticfiles:
  mediafiles:
networks:
  db-network:
  api-network:
