version: "3.7"
services:
  db:
    container_name: ct-db
    image: postgres:12.2
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db-network
  dbadmin:
    container_name: ct-dbadmin
    image: dpage/pgadmin4:4.21
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8181:80
    networks:
      - db-network
    links:
      - db
    depends_on:
      - db
  api:
    container_name: ct-api
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        APP_USER: api
    env_file: api/.env
    command: tail -f /dev/null
    volumes:
      - .:/home/api/src/
    networks:
      - db-network
      - api-network
    links:
      - db
    depends_on:
      - db
  proxy:
    container_name: ct-proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
    volumes:
      - ./api/staticfiles:/srv/staticfiles
      - ./api/mediafiles:/srv/mediafiles
    ports:
      - 8100:80
    networks:
      - api-network
    links:
      - api
volumes:
  db-data:
networks:
  db-network:
  api-network:
