version: "3.7"
services:
  db:
    container_name: db-container
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - backend
  django:
    container_name: django-container
    build:
      context: ./api/
      dockerfile: Dockerfile
      args:
        APP_USER: django
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    environment:
      DEBUG: 1
      SECRET_KEY: 'k99hm7re(68t0!@g&c!$eq!hlut8+gpm%$n%ath&874%j+o_2z'
      DATABASE_URL: 'postgres://postgres:postgres@db/data'
      EMAIL_URL: 'console:'
    volumes:
      - ./api/:/home/django/src/
    ports:
      - 8000:8000
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  dbadmin:
    container_name: dbadmin-container
    image: dpage/pgadmin4:4.21
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8080:80
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
volumes:
  db-data:
networks:
  backend:
