version: "3.7"
services:
  db:
    container_name: db-container
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - backend
  django:
    container_name: django-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_USER: django
    command: tail -f /dev/null
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:postgres@db/data
    volumes:
      - .:/home/django/src/
    ports:
      - 8000:8000
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
  dbadmin:
    container_name: dbadmin-container
    image: dpage/pgadmin4:4.21
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8080:80
    networks:
      - backend
    links:
      - db
    depends_on:
      - db
volumes:
  db-data:
networks:
  backend:
